[package]
authors = ["Jacob Haslehurst <jacob@haslehurst.net>"]
edition = "2018"
name = "roller-web-ui"
readme = "README.md"
repository = "https://jacobh/roller"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "^0.2"
yew = { version = "0.14", features = ["web_sys"] }
