[workspace]

members = [
    "midi",
    "roller",
    "ola_client",
    "roller_protocol",
    "roller_web",
]

exclude = ["web_ui"]

# [profile.release]
# lto = "fat"
# codegen-units = 1
# panic = "abort"
