[package]
name = "midi"
version = "0.1.0"
authors = ["Jacob Haslehurst <jacob@haslehurst.net>"]
edition = "2018"

[dependencies]
num-traits = "*"
num-derive = "*"
async-std = "*"
thiserror = "1.0"
serde = "1.0"

[target.'cfg(macos)'.dependencies]
coremidi = "*"
