[package]
name = "midi"
version = "0.1.0"
authors = ["Jacob Haslehurst <jacob@haslehurst.net>"]
edition = "2018"

[dependencies]
num-traits = "*"
num-derive = "*"
async-std = { version = "*", features = ["unstable"] }
thiserror = "1.0"
serde = { version = "*", features = ["derive"] }

[target.'cfg(target_os = "macos")'.dependencies]
coremidi = "*"
