[package]
name = "roller_protocol"
version = "0.1.0"
authors = ["Jacob Haslehurst <jacob@haslehurst.net>"]
edition = "2018"

[dependencies]
thiserror = "1.0"
serde = "1.0"
derive_more = "*"
indexmap = "*"
rustc-hash = "*"
palette = "*"
