name: Roller

on:
  push:
    branches: "**"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache target dirs
      uses: actions/cache@v2
      with:
        path: |
          **/target
        key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
    - name: Check
      run: cargo check --verbose
