name: Rust

on:
  push:
    branches: "**"
  pull_request:
    branches: "**"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check
      # we're just checking the libs as there's some sort of bug causing cargo to attempt to check macos dependencies on linux
      run: cargo check --lib --verbose
