name: Rust

on:
  push:
    branches: "**"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install wasm32 target
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          target: wasm32-unknown-unknown
    - name: Cache target dirs
      uses: actions/cache@v2
      with:
        path: |
          **/target
        key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
    - name: Check
      # we're just checking the libs as there's some sort of bug causing cargo to attempt to check macos dependencies on linux
      run: cargo check --verbose
    - name: Check Web UI
      run: (cd web_ui && make check)
