name: Roller

on:
  push:
    branches: "**"

env:
  CARGO_TERM_COLOR: always

jobs:
  roller:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check
      run: cargo check --verbose

  web_ui:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install wasm32 target
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          default: true
          target: wasm32-unknown-unknown
    - name: Check Web UI
      working-directory: ./web_ui
      run: make check
